// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	request "github.com/felixlambertv/go-cleanplate/internal/controller/request"
	mock "github.com/stretchr/testify/mock"
)

// IMailService is an autogenerated mock type for the IMailService type
type IMailService struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: emailData
func (_m *IMailService) SendEmail(emailData request.SendEmailRequest) error {
	ret := _m.Called(emailData)

	var r0 error
	if rf, ok := ret.Get(0).(func(request.SendEmailRequest) error); ok {
		r0 = rf(emailData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIMailService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIMailService creates a new instance of IMailService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIMailService(t mockConstructorTestingTNewIMailService) *IMailService {
	mock := &IMailService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
