// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	model "github.com/felixlambertv/go-cleanplate/internal/model"
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"

	request "github.com/felixlambertv/go-cleanplate/internal/controller/request"

	response "github.com/felixlambertv/go-cleanplate/internal/controller/response"

	service "github.com/felixlambertv/go-cleanplate/internal/service"
)

// IUserService is an autogenerated mock type for the IUserService type
type IUserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: req
func (_m *IUserService) CreateUser(req request.CreateUserRequest) (*response.UserResponse, error) {
	ret := _m.Called(req)

	var r0 *response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.CreateUserRequest) (*response.UserResponse, error)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(request.CreateUserRequest) *response.UserResponse); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(request.CreateUserRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteUser provides a mock function with given fields: id
func (_m *IUserService) DeleteUser(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetUser provides a mock function with given fields: id
func (_m *IUserService) GetUser(id uint) (*response.UserResponse, error) {
	ret := _m.Called(id)

	var r0 *response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*response.UserResponse, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uint) *response.UserResponse); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUsers provides a mock function with given fields: paginationReq
func (_m *IUserService) GetUsers(paginationReq model.Pagination) (*model.Pagination, error) {
	ret := _m.Called(paginationReq)

	var r0 *model.Pagination
	var r1 error
	if rf, ok := ret.Get(0).(func(model.Pagination) (*model.Pagination, error)); ok {
		return rf(paginationReq)
	}
	if rf, ok := ret.Get(0).(func(model.Pagination) *model.Pagination); ok {
		r0 = rf(paginationReq)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Pagination)
		}
	}

	if rf, ok := ret.Get(1).(func(model.Pagination) error); ok {
		r1 = rf(paginationReq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUserCountry provides a mock function with given fields: req, userID
func (_m *IUserService) UpdateUserCountry(req request.UpdateUserCountryRequest, userID uint) (*response.UserResponse, error) {
	ret := _m.Called(req, userID)

	var r0 *response.UserResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(request.UpdateUserCountryRequest, uint) (*response.UserResponse, error)); ok {
		return rf(req, userID)
	}
	if rf, ok := ret.Get(0).(func(request.UpdateUserCountryRequest, uint) *response.UserResponse); ok {
		r0 = rf(req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*response.UserResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(request.UpdateUserCountryRequest, uint) error); ok {
		r1 = rf(req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTrx provides a mock function with given fields: trxHandle
func (_m *IUserService) WithTrx(trxHandle *gorm.DB) service.IUserService {
	ret := _m.Called(trxHandle)

	var r0 service.IUserService
	if rf, ok := ret.Get(0).(func(*gorm.DB) service.IUserService); ok {
		r0 = rf(trxHandle)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(service.IUserService)
		}
	}

	return r0
}

type mockConstructorTestingTNewIUserService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIUserService creates a new instance of IUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIUserService(t mockConstructorTestingTNewIUserService) *IUserService {
	mock := &IUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
